spring:
  datasource:
    url: jdbc:mysql://rm-uf6470s9615e13hc4no.mysql.rds.aliyuncs.com/wikidev
    username: wikidev
    password: wikidevABC123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.ivy.wiki.entiry
  mapper-locations: classpath:mapper/*.xml