spring:
  datasource:
#    url: jdbc:mysql://rm-uf6470s9615e13hc4no.mysql.rds.aliyuncs.com/wikidev
#    username: wikidev
#    password: wikidevABC123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wikidev
    username: root
    password: root

mybatis:
  type-aliases-package: com.ivy.wiki.entiry
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true